# 配置文件加密key 生产环境中可通过环境变量、命令行等形式进行设置
jasypt:
  encryptor:
    password: yboot

server:
  port: 9202
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  application:
    name: yboot-business-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          # 用来指定topic
          destination: add-bonus
  # 数据源
  datasource:
    url: jdbc:mysql://192.168.4.26:3306/yboot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    # Jasypt加密 可到common-utils中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果) 以下解密结果为123456
    password: ENC(k+VW13mKckDfgCK00mqFAS2/8RpaMHHWrfjPOKIKLbtR1DZVHu29T/iVV1yHJFfw)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
#     Druid StatViewServlet配置
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: ENC(k+VW13mKckDfgCK00mqFAS2/8RpaMHHWrfjPOKIKLbtR1DZVHu29T/iVV1yHJFfw)
        # IP白名单 多个逗号分隔
        allow:
        # IP黑名单
        deny:
      filter:
        stat:
          # 开启监控sql
          enabled: true
          # 显示并标注慢sql 默认当超过3秒显示
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        # 防SQL注入过滤
        wall:
          config:
            # 允许多条sql同时执行
            multi-statement-allow: true
  jpa:
    # 显示sql
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: update
  # Redis
  redis:
    host: 127.0.0.1
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    # 超时时间 Duration类型 3秒
    timeout: 3S
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false
  boot:
    admin:
      # 修改上下文路径
      context-path: /base/admin
      client:
        url: http://127.0.0.1:${server.port}/base/admin

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml



security:
  oauth2:
    client:
      client-id: yboot
      client-secret: 123456
    resource:
      jwt:
        key-uri: http://127.0.0.1:8888/oauth/token_key

# 日志
logging:
  # 输出级别
  level:
#    root: info
    com.yboot.business.client: debug

# Swagger界面内容配置
swagger:
  title: base API接口文档
  description: base Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://www.budongfeng.com
  contact:
    name: 田培融
    url: http://www.budongfeng.com
    email: canghaihongxin@163.com
# feign相关配置
feign:
#  sentinel:
    # 为feign整合sentinel
#    enabled: true
  client:
    config:
      default:
        loggerLevel: basic
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

client:
  support:
    spring:
      datasource:
        autoproxy: true